### ISSUE TITLE
Can't locate GDBM_File.pm

### ISSUE THREAD

**Issue by romildo** [trizen/fbmenugen#2]
I am trying to use `fbmenugen` on [NixOS](https://nixos.org/), but the scrip fails with a message saying that `GDBM_File.pm` cannot be found. It seems that it is not available in the perl installation. For more information see also https://github.com/NixOS/nixpkgs/issues/4311.

There would be a workaround for this issues?

**Comment by trizen** [comment]
I tried to address the issue in https://github.com/trizen/fbmenugen/commit/ed9a680546edbb5b05086971b6a9f42a37cb485f. If you can confirm the fix, that would be great.

Thanks for reporting.

**Comment by romildo** [comment]
Thanks for the quick fix. It works now.

Probably a similar fix would be welcome for `obmenu_generator` as well.

**Comment by trizen** [comment]
Thanks for the confirmation. I will try to add this to obmenu-generator as well.
