### ISSUE TITLE
Fluxbox does not use PNG icons. Fluxbox uses XPM icon files.

### ISSUE THREAD

**Issue by chazbroam** [trizen/fbmenugen#4]
FBmenugen needs to generate a cache of XPM icons, not PNG icons. Then generate a menu file pointing to XPM icons in fbmenugen's icon cache.

**Comment by chazbroam** [comment]
Workaround: 
1) mass convert FBmenugen's icon folder (~/.config/fbmenugen/icons), all PNG to XPM. Mogrify or Imagemagic will do it.
2) generate new static menu with icons.
3) in any good text editor, search ~/fluxbox/menu file (Control+F) for "png", and replace with "xpm". Replace all at once. Save changes.
4) right click, and enjoy your new menu WITH ICONS.

**Comment by chazbroam** [comment]
New version of fbmenugen (0.88) breaks workaround, and does not fix issue. FORCES ME TO REVERT BACK TO VERSION 0.87!!! 

Are you even paying attention to issues?!?!?!?

**Comment by trizen** [comment]
The icons are now cached in the `~/.cache/fbmenugen/icons` folder.

The version of Fluxbox provided by Arch Linux supports PNG images. Also, it does not seem possible to convert images to XPM format with the Gtk3 library.

**Comment by chazbroam** [comment]
On Slackware. Had to rebuild Fluxbox with imlib2. Now everything works.

**Comment by chazbroam** [comment]
Problem solved.
